import { SIDECAR_BASE } from '../hooks/useSidecar'

interface StoreState {
  user: any
  overallRisk: any
  apps: any[]
  connections: any[]
  cookies: any[]
  lastScanAt: string | null
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function riskColor(level: string): string {
  switch (level?.toUpperCase()) {
    case 'LOW':    return '#10B981'
    case 'MEDIUM': return '#F59E0B'
    case 'HIGH':   return '#EF4444'
    case 'SEVERE': return '#7C3AED'
    default:       return '#9CA3AF'
  }
}

function riskBg(level: string): string {
  switch (level?.toUpperCase()) {
    case 'LOW':    return '#10B98122'
    case 'MEDIUM': return '#F59E0B22'
    case 'HIGH':   return '#EF444422'
    case 'SEVERE': return '#7C3AED22'
    default:       return '#9CA3AF22'
  }
}

function jurisdictionFlag(j: string): string {
  const flags: Record<string, string> = {
    US: '🇺🇸', EU: '🇪🇺', GB: '🇬🇧', CN: '🇨🇳', RU: '🇷🇺',
    DE: '🇩🇪', FR: '🇫🇷', NL: '🇳🇱', IE: '🇮🇪', SE: '🇸🇪',
    CH: '🇨🇭', CA: '🇨🇦', AU: '🇦🇺', JP: '🇯🇵', KR: '🇰🇷',
    SG: '🇸🇬', IN: '🇮🇳', BR: '🇧🇷', Unknown: '🌐',
  }
  return flags[j] || flags[j?.toUpperCase()] || '🌐'
}

function fmt(date: Date): string {
  return date.toLocaleDateString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

function esc(s: any): string {
  if (s == null) return '—'
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function scoreToColor(score: number): string {
  if (score >= 80) return '#10B981'
  if (score >= 60) return '#F59E0B'
  if (score >= 40) return '#EF4444'
  return '#7C3AED'
}

// ─── Page builders ────────────────────────────────────────────────────────────

function buildCover(data: any): string {
  const { user, overall, generatedAt } = data
  const score = overall?.sovereignty_score ?? overall?.score ?? 0
  const riskLevel = overall?.risk_level ?? (score >= 80 ? 'LOW' : score >= 60 ? 'MEDIUM' : score >= 40 ? 'HIGH' : 'SEVERE')
  const color = scoreToColor(score)
  // SVG circle: circumference = 2π×45 ≈ 282.7
  const circ = 282.7
  const offset = circ - (score / 100) * circ

  return `
  <!-- COVER PAGE -->
  <div class="page cover-page">
    <!-- Dark header -->
    <div class="cover-header">
      <div class="cover-logo-row">
        <svg width="40" height="40" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
          <circle cx="16" cy="16" r="16" fill="#1e293b"/>
          <path d="M16 4L6 8.5v7.5c0 6.3 4.3 12.2 10 13.6C21.7 28.2 26 22.3 26 16V8.5L16 4z" fill="#3B82F6" opacity="0.9"/>
          <path d="M16 7L8 11v5.5c0 4.6 3.1 9 8 9.9V7z" fill="white" opacity="0.12"/>
          <path d="M12.5 16.5l2.5 2.5 5-5" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
        </svg>
        <div>
          <div class="cover-title">DOXSHIELD</div>
          <div class="cover-subtitle">Data Sovereignty Report</div>
        </div>
      </div>
    </div>

    <!-- Score section -->
    <div class="cover-score-section">
      <div class="score-circle-wrap">
        <svg width="140" height="140" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="45" fill="none" stroke="#e2e8f0" stroke-width="8"/>
          <circle cx="50" cy="50" r="45" fill="none" stroke="${color}" stroke-width="8"
            stroke-dasharray="${circ}" stroke-dashoffset="${offset}"
            stroke-linecap="round"
            transform="rotate(-90 50 50)"/>
          <text x="50" y="46" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
            font-size="22" font-weight="700" fill="${color}">${score}</text>
          <text x="50" y="60" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
            font-size="9" fill="#64748b">out of 100</text>
        </svg>
      </div>
      <div class="score-label">Sovereignty Score</div>
      <div class="risk-badge" style="background:${riskBg(riskLevel)};color:${riskColor(riskLevel)};border:1.5px solid ${riskColor(riskLevel)}44;">
        ${esc(riskLevel)} RISK
      </div>
    </div>

    <!-- Meta info -->
    <div class="cover-meta">
      <div class="cover-meta-row">
        <span class="meta-label">Generated by</span>
        <span class="meta-value">${esc(user?.name || user?.email || 'Doxshield User')}</span>
      </div>
      ${user?.email ? `<div class="cover-meta-row">
        <span class="meta-label">Email</span>
        <span class="meta-value">${esc(user.email)}</span>
      </div>` : ''}
      <div class="cover-meta-row">
        <span class="meta-label">Generated at</span>
        <span class="meta-value">${fmt(generatedAt)}</span>
      </div>
      <div class="cover-meta-row">
        <span class="meta-label">Report type</span>
        <span class="meta-value">Full Privacy Audit</span>
      </div>
    </div>

    <div class="cover-footer">Confidential — Generated by Doxshield · Data Sovereignty Monitor</div>
  </div>`
}

function buildExecSummary(data: any): string {
  const { overall, apps, connections, cookies, cookieStats, lastScanAt } = data
  const score = overall?.sovereignty_score ?? overall?.score ?? 0
  const riskLevel = overall?.risk_level ?? 'UNKNOWN'

  const totalApps = apps?.length ?? 0
  const activeConns = connections?.length ?? 0
  const totalCookies = cookies?.length ?? cookieStats?.total ?? 0
  const trackers = cookies?.filter((c: any) => c.known_tracker).length ?? cookieStats?.trackers ?? 0
  const euSafe = cookies?.filter((c: any) => ['EU', 'DE', 'FR', 'NL', 'IE', 'SE', 'FI', 'DK', 'AT', 'BE'].includes(c.jurisdiction?.toUpperCase())).length ?? 0
  const thirdParty = cookies?.filter((c: any) => c.is_third_party).length ?? 0

  const appRiskScore = overall?.app_risk_score ?? overall?.app_score ?? 0
  const networkRiskScore = overall?.network_risk_score ?? overall?.network_score ?? 0
  const cookieRiskScore = overall?.cookie_risk_score ?? overall?.cookie_score ?? 0

  const topRiskApps: any[] = overall?.top_risk_apps ?? apps?.slice(0, 3) ?? []

  // Auto-generate key findings
  const findings: string[] = []
  const cnCookies = cookies?.filter((c: any) => c.jurisdiction?.toUpperCase() === 'CN').length ?? 0
  const ruCookies = cookies?.filter((c: any) => c.jurisdiction?.toUpperCase() === 'RU').length ?? 0
  const vpnConn = connections?.find((c: any) => c.vpn || c.is_vpn || c.app?.toLowerCase().includes('vpn') || c.remote_host?.toLowerCase().includes('vpn'))
  const fbCookies = cookies?.filter((c: any) => c.domain?.includes('facebook') || c.domain?.includes('instagram')).length ?? 0
  const severeApps = apps?.filter((a: any) => a.risk_level?.toUpperCase() === 'SEVERE').length ?? 0
  const highApps = apps?.filter((a: any) => a.risk_level?.toUpperCase() === 'HIGH').length ?? 0

  if (cnCookies > 0) findings.push(`${cnCookies} cookie${cnCookies > 1 ? 's' : ''} from Chinese-jurisdictions companies detected — subject to Chinese data-sharing law`)
  if (ruCookies > 0) findings.push(`${ruCookies} cookie${ruCookies > 1 ? 's' : ''} from Russian-jurisdiction companies detected`)
  if (vpnConn) findings.push(`VPN activity detected — traffic may be routed through ${vpnConn.country || 'unknown'} jurisdiction`)
  if (trackers > 0) findings.push(`${trackers} third-party tracker${trackers > 1 ? 's' : ''} found across your browsers`)
  if (fbCookies > 0) findings.push(`${fbCookies} Facebook/Meta tracking cookie${fbCookies > 1 ? 's' : ''} present`)
  if (severeApps > 0) findings.push(`${severeApps} application${severeApps > 1 ? 's' : ''} rated SEVERE risk`)
  if (highApps > 0 && findings.length < 5) findings.push(`${highApps} application${highApps > 1 ? 's' : ''} rated HIGH risk`)
  if (score < 50 && findings.length < 5) findings.push(`Sovereignty score of ${score}/100 is below recommended threshold of 60`)
  if (findings.length === 0) findings.push(`Sovereignty score: ${score}/100 — system appears healthy`)

  const metricsData = [
    { label: 'Sovereignty Score', value: `${score}/100`, color: scoreToColor(score) },
    { label: 'Apps Analyzed', value: String(totalApps), color: '#3B82F6' },
    { label: 'Active Connections', value: String(activeConns), color: '#3B82F6' },
    { label: 'Cookies Scanned', value: String(totalCookies), color: '#3B82F6' },
    { label: 'Trackers Found', value: String(trackers), color: trackers > 0 ? '#EF4444' : '#10B981' },
    { label: 'EU-Safe Cookies', value: String(euSafe), color: '#10B981' },
  ]

  return `
  <!-- PAGE 2: EXECUTIVE SUMMARY -->
  <div class="page">
    <div class="page-header">
      <div class="page-header-left">
        <div class="section-eyebrow">Executive Summary</div>
        <h1 class="section-title">Privacy Audit Overview</h1>
      </div>
      <div class="risk-badge-lg" style="background:${riskBg(riskLevel)};color:${riskColor(riskLevel)};border:1.5px solid ${riskColor(riskLevel)}44;">
        ${esc(riskLevel)}
      </div>
    </div>

    <!-- Metric cards 3x2 -->
    <div class="metric-grid">
      ${metricsData.map(m => `
      <div class="metric-card" style="border-left: 3px solid ${m.color};">
        <div class="metric-value" style="color:${m.color}">${esc(m.value)}</div>
        <div class="metric-label">${esc(m.label)}</div>
      </div>`).join('')}
    </div>

    <!-- Risk breakdown -->
    <div class="sub-section">
      <h3 class="sub-heading">Risk Score Breakdown</h3>
      <div class="risk-bars">
        ${[
          { label: 'App Risk Score', score: appRiskScore },
          { label: 'Network Risk Score', score: networkRiskScore },
          { label: 'Cookie Risk Score', score: cookieRiskScore },
        ].map(r => {
          const lvl = r.score >= 75 ? 'SEVERE' : r.score >= 50 ? 'HIGH' : r.score >= 25 ? 'MEDIUM' : 'LOW'
          return `
        <div class="risk-bar-row">
          <span class="risk-bar-label">${esc(r.label)}</span>
          <div class="risk-bar-track">
            <div class="risk-bar-fill" style="width:${Math.min(r.score, 100)}%;background:${riskColor(lvl)};"></div>
          </div>
          <span class="risk-bar-score" style="color:${riskColor(lvl)}">${r.score}</span>
        </div>`
        }).join('')}
      </div>
    </div>

    <!-- Top risk apps -->
    ${topRiskApps.length > 0 ? `
    <div class="sub-section">
      <h3 class="sub-heading">Top Risk Applications</h3>
      <div class="top-apps-list">
        ${topRiskApps.slice(0, 5).map((a: any, i: number) => {
          const appName = a.app_name ?? a.name ?? a
          const appScore = a.risk_score ?? a.score ?? '—'
          const appLevel = a.risk_level ?? '—'
          const appFactor = a.top_risk_factor ?? a.risk_factor ?? ''
          return `
        <div class="top-app-row">
          <span class="top-app-rank">${i + 1}</span>
          <span class="top-app-name">${esc(appName)}</span>
          <span class="top-app-score" style="color:${riskColor(appLevel)}">${esc(appScore)}</span>
          <span class="risk-pill" style="background:${riskBg(appLevel)};color:${riskColor(appLevel)}">${esc(appLevel)}</span>
          ${appFactor ? `<span class="top-app-factor">${esc(appFactor)}</span>` : ''}
        </div>`
        }).join('')}
      </div>
    </div>` : ''}

    <!-- Key findings -->
    <div class="sub-section">
      <h3 class="sub-heading">Key Findings</h3>
      <ul class="findings-list">
        ${findings.map(f => `<li>${esc(f)}</li>`).join('')}
      </ul>
    </div>

    ${lastScanAt ? `<p class="scan-note">Last scan: ${esc(lastScanAt)}</p>` : ''}

    <div class="page-footer">
      Doxshield &middot; Data Sovereignty Report &middot; ${fmt(data.generatedAt)} &middot; Page <span class="pagenum"></span>
    </div>
  </div>`
}

function buildAppAnalysis(data: any): string {
  const { apps, lastScanAt } = data
  const sorted = [...(apps || [])].sort((a, b) => (b.risk_score ?? 0) - (a.risk_score ?? 0)).slice(0, 20)

  return `
  <!-- PAGE 3: APPLICATION ANALYSIS -->
  <div class="page">
    <div class="page-header">
      <div class="page-header-left">
        <div class="section-eyebrow">Application Analysis</div>
        <h1 class="section-title">Installed App Risk Assessment</h1>
      </div>
    </div>

    <p class="section-desc">
      ${sorted.length} application${sorted.length !== 1 ? 's' : ''} analysed${lastScanAt ? ` · Last scan: ${esc(lastScanAt)}` : ''}.
      Sorted by risk score (highest first). Showing up to 20 applications.
    </p>

    <table class="data-table">
      <thead>
        <tr>
          <th>Application</th>
          <th>Jurisdiction</th>
          <th style="text-align:center">Risk Score</th>
          <th style="text-align:center">Risk Level</th>
          <th>Top Risk Factor</th>
        </tr>
      </thead>
      <tbody>
        ${sorted.length === 0
          ? `<tr><td colspan="5" style="text-align:center;color:#9CA3AF;padding:24px">No application data available</td></tr>`
          : sorted.map((a: any, i: number) => {
              const name = a.app_name ?? a.name ?? '—'
              const jur = a.jurisdiction ?? '—'
              const score = a.risk_score ?? '—'
              const level = a.risk_level ?? '—'
              const factor = a.top_risk_factor ?? a.risk_factor ?? '—'
              return `
        <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
          <td class="app-name-cell">
            <strong>${esc(name)}</strong>
          </td>
          <td>${jurisdictionFlag(jur)} ${esc(jur)}</td>
          <td style="text-align:center;font-weight:600;color:${riskColor(level)}">${esc(score)}</td>
          <td style="text-align:center">
            <span class="risk-pill" style="background:${riskBg(level)};color:${riskColor(level)}">${esc(level)}</span>
          </td>
          <td style="font-size:11px;color:#475569">${esc(factor)}</td>
        </tr>`
            }).join('')}
      </tbody>
    </table>

    ${apps?.length > 20 ? `<p class="scan-note">Showing top 20 of ${apps.length} apps. Export JSON for the full list.</p>` : ''}

    <div class="page-footer">
      Doxshield &middot; Data Sovereignty Report &middot; ${fmt(data.generatedAt)} &middot; Page <span class="pagenum"></span>
    </div>
  </div>`
}

function buildNetworkAnalysis(data: any): string {
  const { connections } = data
  const conns: any[] = connections || []

  const countries = [...new Set(conns.map((c: any) => c.country).filter(Boolean))]
  const sorted = [...conns]
    .sort((a, b) => (b.risk ?? b.risk_score ?? 0) - (a.risk ?? a.risk_score ?? 0))
    .slice(0, 25)

  const vpnConn = conns.find((c: any) =>
    c.vpn || c.is_vpn ||
    c.app?.toLowerCase().includes('vpn') ||
    c.remote_host?.toLowerCase().includes('vpn') ||
    c.app?.toLowerCase().includes('wireguard') ||
    c.app?.toLowerCase().includes('nordvpn') ||
    c.app?.toLowerCase().includes('expressvpn')
  )

  return `
  <!-- PAGE 4: NETWORK CONNECTIONS -->
  <div class="page">
    <div class="page-header">
      <div class="page-header-left">
        <div class="section-eyebrow">Network Analysis</div>
        <h1 class="section-title">Active Network Connections</h1>
      </div>
    </div>

    <p class="section-desc">
      ${conns.length} active connection${conns.length !== 1 ? 's' : ''} across
      ${countries.length} countr${countries.length !== 1 ? 'ies' : 'y'}.
      Showing top 25 by risk. Countries: ${countries.slice(0, 8).map(esc).join(', ')}${countries.length > 8 ? '…' : ''}.
    </p>

    ${vpnConn ? `
    <div class="vpn-box">
      <div class="vpn-box-title">🔒 VPN Detected</div>
      <div class="vpn-box-body">
        <strong>${esc(vpnConn.app ?? 'VPN Client')}</strong>
        is routing traffic${vpnConn.country ? ` through <strong>${esc(vpnConn.country)}</strong>` : ''}.
        ${vpnConn.remote_host ? `Remote: ${esc(vpnConn.remote_host)}` : ''}
        — Verify this jurisdiction aligns with your privacy requirements.
      </div>
    </div>` : ''}

    <table class="data-table">
      <thead>
        <tr>
          <th>Application</th>
          <th>Remote Host / IP</th>
          <th>Country</th>
          <th style="text-align:center">Port</th>
          <th style="text-align:center">Risk</th>
        </tr>
      </thead>
      <tbody>
        ${sorted.length === 0
          ? `<tr><td colspan="5" style="text-align:center;color:#9CA3AF;padding:24px">No active connection data</td></tr>`
          : sorted.map((c: any, i: number) => {
              const app = c.app ?? c.process ?? '—'
              const host = c.remote_host ?? c.remote_ip ?? c.ip ?? '—'
              const country = c.country ?? '—'
              const port = c.remote_port ?? c.port ?? '—'
              const risk = c.risk ?? c.risk_score ?? '—'
              const riskLevel = typeof risk === 'number'
                ? (risk >= 75 ? 'SEVERE' : risk >= 50 ? 'HIGH' : risk >= 25 ? 'MEDIUM' : 'LOW')
                : '—'
              return `
        <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
          <td><strong>${esc(app)}</strong></td>
          <td style="font-family:monospace;font-size:11px">${esc(host)}</td>
          <td>${jurisdictionFlag(country)} ${esc(country)}</td>
          <td style="text-align:center;font-family:monospace;font-size:11px">${esc(port)}</td>
          <td style="text-align:center">
            ${typeof risk === 'number'
              ? `<span class="risk-pill" style="background:${riskBg(riskLevel)};color:${riskColor(riskLevel)}">${risk}</span>`
              : `<span style="color:#9CA3AF">—</span>`}
          </td>
        </tr>`
            }).join('')}
      </tbody>
    </table>

    ${conns.length > 25 ? `<p class="scan-note">Showing top 25 of ${conns.length} connections by risk score.</p>` : ''}

    <div class="page-footer">
      Doxshield &middot; Data Sovereignty Report &middot; ${fmt(data.generatedAt)} &middot; Page <span class="pagenum"></span>
    </div>
  </div>`
}

function buildCookieAnalysis(data: any): string {
  const { cookies, cookieStats } = data
  const allCookies: any[] = cookies || []

  const total = allCookies.length || cookieStats?.total || 0
  const thirdPartyCount = allCookies.filter((c: any) => c.is_third_party).length
  const trackers = allCookies.filter((c: any) => c.known_tracker)
  const euSafe = allCookies.filter((c: any) =>
    ['EU', 'DE', 'FR', 'NL', 'IE', 'SE', 'FI', 'DK', 'AT', 'BE', 'GB'].includes(c.jurisdiction?.toUpperCase())
  )

  const thirdPartyPct = total > 0 ? Math.round((thirdPartyCount / total) * 100) : 0

  // By jurisdiction
  const byJur: Record<string, number> = {}
  allCookies.forEach((c: any) => { const j = c.jurisdiction || 'Unknown'; byJur[j] = (byJur[j] || 0) + 1 })
  const jurRows = Object.entries(byJur).sort(([, a], [, b]) => b - a)

  // By browser
  const byBrowser: Record<string, number> = {}
  allCookies.forEach((c: any) => { const b = c.browser || c.source || 'Unknown'; byBrowser[b] = (byBrowser[b] || 0) + 1 })
  const browserRows = Object.entries(byBrowser).sort(([, a], [, b]) => b - a)

  // High-risk cookies (CN/RU + SEVERE/HIGH)
  const highRisk = allCookies
    .filter((c: any) =>
      ['CN', 'RU'].includes(c.jurisdiction?.toUpperCase()) ||
      ['SEVERE', 'HIGH'].includes(c.risk_level?.toUpperCase())
    )
    .slice(0, 15)

  const trackerList = trackers.slice(0, 15)

  return `
  <!-- PAGE 5: COOKIE ANALYSIS -->
  <div class="page">
    <div class="page-header">
      <div class="page-header-left">
        <div class="section-eyebrow">Cookie &amp; Tracker Analysis</div>
        <h1 class="section-title">Browser Cookie Audit</h1>
      </div>
    </div>

    <!-- 4 stat boxes -->
    <div class="stat-boxes">
      <div class="stat-box">
        <div class="stat-value" style="color:#3B82F6">${total}</div>
        <div class="stat-label">Total Cookies</div>
      </div>
      <div class="stat-box">
        <div class="stat-value" style="color:${thirdPartyPct > 50 ? '#EF4444' : '#F59E0B'}">${thirdPartyPct}%</div>
        <div class="stat-label">Third-Party</div>
      </div>
      <div class="stat-box">
        <div class="stat-value" style="color:${trackers.length > 0 ? '#EF4444' : '#10B981'}">${trackers.length}</div>
        <div class="stat-label">Trackers</div>
      </div>
      <div class="stat-box">
        <div class="stat-value" style="color:#10B981">${euSafe.length}</div>
        <div class="stat-label">EU-Safe</div>
      </div>
    </div>

    <div class="two-col">
      <!-- By Jurisdiction -->
      <div>
        <h3 class="sub-heading">By Jurisdiction</h3>
        <table class="data-table" style="font-size:11px">
          <thead><tr><th>Jurisdiction</th><th style="text-align:right">Cookies</th><th style="text-align:right">% of Total</th></tr></thead>
          <tbody>
            ${jurRows.length === 0
              ? `<tr><td colspan="3" style="text-align:center;color:#9CA3AF">No data</td></tr>`
              : jurRows.map(([j, n], i) => `
            <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
              <td>${jurisdictionFlag(j)} ${esc(j)}</td>
              <td style="text-align:right;font-weight:600">${n}</td>
              <td style="text-align:right;color:#64748b">${total > 0 ? Math.round((n / total) * 100) : 0}%</td>
            </tr>`).join('')}
          </tbody>
        </table>
      </div>

      <!-- By Browser -->
      <div>
        <h3 class="sub-heading">By Browser</h3>
        <table class="data-table" style="font-size:11px">
          <thead><tr><th>Browser</th><th style="text-align:right">Cookies</th></tr></thead>
          <tbody>
            ${browserRows.length === 0
              ? `<tr><td colspan="2" style="text-align:center;color:#9CA3AF">No data</td></tr>`
              : browserRows.map(([b, n], i) => `
            <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
              <td>${esc(b)}</td>
              <td style="text-align:right;font-weight:600">${n}</td>
            </tr>`).join('')}
          </tbody>
        </table>
      </div>
    </div>

    <!-- High-risk cookies -->
    ${highRisk.length > 0 ? `
    <div class="sub-section">
      <h3 class="sub-heading">High-Risk Cookies (CN/RU jurisdiction or HIGH/SEVERE)</h3>
      <table class="data-table" style="font-size:11px">
        <thead>
          <tr>
            <th>Domain</th>
            <th>Name</th>
            <th style="text-align:center">Jurisdiction</th>
            <th style="text-align:center">Risk</th>
            <th>Browser</th>
          </tr>
        </thead>
        <tbody>
          ${highRisk.map((c: any, i: number) => `
          <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
            <td style="font-family:monospace">${esc(c.domain ?? '—')}</td>
            <td style="font-family:monospace">${esc(c.name ?? '—')}</td>
            <td style="text-align:center">${jurisdictionFlag(c.jurisdiction)} ${esc(c.jurisdiction ?? '—')}</td>
            <td style="text-align:center">
              <span class="risk-pill" style="background:${riskBg(c.risk_level)};color:${riskColor(c.risk_level)}">${esc(c.risk_level ?? '—')}</span>
            </td>
            <td>${esc(c.browser ?? c.source ?? '—')}</td>
          </tr>`).join('')}
        </tbody>
      </table>
    </div>` : ''}

    <!-- Tracker list -->
    ${trackerList.length > 0 ? `
    <div class="sub-section">
      <h3 class="sub-heading">Known Trackers</h3>
      <table class="data-table" style="font-size:11px">
        <thead>
          <tr><th>Domain</th><th>Name</th><th>Browser</th><th style="text-align:center">Third-Party</th></tr>
        </thead>
        <tbody>
          ${trackerList.map((c: any, i: number) => `
          <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
            <td style="font-family:monospace">${esc(c.domain ?? '—')}</td>
            <td style="font-family:monospace">${esc(c.name ?? '—')}</td>
            <td>${esc(c.browser ?? c.source ?? '—')}</td>
            <td style="text-align:center">${c.is_third_party ? '✓' : '—'}</td>
          </tr>`).join('')}
        </tbody>
      </table>
    </div>` : ''}

    <div class="page-footer">
      Doxshield &middot; Data Sovereignty Report &middot; ${fmt(data.generatedAt)} &middot; Page <span class="pagenum"></span>
    </div>
  </div>`
}

function buildRecommendations(data: any): string {
  const { apps, cookies, connections, overall } = data
  const score = overall?.sovereignty_score ?? overall?.score ?? 0

  interface Recommendation {
    urgency: 'URGENT' | 'SHORT-TERM' | 'ONGOING'
    text: string
  }

  const recs: Recommendation[] = []

  // CN cookies
  const cnCookies = (cookies || []).filter((c: any) => c.jurisdiction?.toUpperCase() === 'CN')
  const deepseekCookies = cnCookies.filter((c: any) => c.domain?.includes('deepseek') || c.domain?.includes('tiktok') || c.domain?.includes('bytedance'))
  if (deepseekCookies.length > 0) {
    recs.push({ urgency: 'URGENT', text: 'Remove DeepSeek/TikTok cookies — Chinese law requires data sharing with the government. Clear cookies in your browser settings and consider blocking these domains.' })
  } else if (cnCookies.length > 0) {
    recs.push({ urgency: 'URGENT', text: `Remove ${cnCookies.length} Chinese-jurisdiction cookie${cnCookies.length > 1 ? 's' : ''} — companies operating under Chinese law must share user data with authorities upon request.` })
  }

  // RU cookies
  const ruCookies = (cookies || []).filter((c: any) => c.jurisdiction?.toUpperCase() === 'RU')
  if (ruCookies.length > 0) {
    recs.push({ urgency: 'URGENT', text: `Remove ${ruCookies.length} Russian-jurisdiction cookie${ruCookies.length > 1 ? 's' : ''} — Russian law requires local data storage and access for government agencies.` })
  }

  // Facebook/Meta
  const fbCookies = (cookies || []).filter((c: any) => c.domain?.includes('facebook') || c.domain?.includes('instagram') || c.domain?.includes('meta'))
  if (fbCookies.length > 0) {
    recs.push({ urgency: 'SHORT-TERM', text: 'Consider blocking Facebook/Meta trackers using a browser extension like uBlock Origin or Privacy Badger to reduce cross-site tracking.' })
  }

  // SEVERE/HIGH apps
  const severeApps = (apps || []).filter((a: any) => ['SEVERE', 'HIGH'].includes(a.risk_level?.toUpperCase())).slice(0, 4)
  severeApps.forEach((a: any) => {
    const name = a.app_name ?? a.name ?? 'Unknown App'
    const factor = a.top_risk_factor ?? a.risk_factor ?? 'data collection practices'
    recs.push({ urgency: a.risk_level?.toUpperCase() === 'SEVERE' ? 'URGENT' : 'SHORT-TERM', text: `Review ${name} — ${factor}. Consider whether this app is necessary or if a privacy-respecting alternative exists.` })
  })

  // VPN
  const vpnConn = (connections || []).find((c: any) =>
    c.vpn || c.is_vpn || c.app?.toLowerCase().includes('vpn') ||
    c.app?.toLowerCase().includes('wireguard') || c.app?.toLowerCase().includes('nordvpn')
  )
  if (vpnConn) {
    recs.push({ urgency: 'ONGOING', text: `Your VPN (${vpnConn.app || 'VPN Client'}) routes traffic through ${vpnConn.country || 'an unknown jurisdiction'} — verify this aligns with your privacy needs and that your VPN provider has a verified no-logs policy.` })
  }

  // Low sovereignty score
  if (score < 50) {
    recs.push({ urgency: 'SHORT-TERM', text: `Your sovereignty score of ${score}/100 is below the recommended threshold. Consider switching to EU-based software alternatives (e.g., Proton for email, Nextcloud for storage, DuckDuckGo for search).` })
  }

  // No FDA / Safari cookies
  const hasSafariCookies = (cookies || []).some((c: any) => c.browser?.toLowerCase().includes('safari') || c.source?.toLowerCase().includes('safari'))
  if (!hasSafariCookies) {
    recs.push({ urgency: 'ONGOING', text: 'Grant Full Disk Access to Doxshield in System Settings → Privacy & Security → Full Disk Access to enable complete Safari cookie scanning.' })
  }

  // Trackers
  const trackerCount = (cookies || []).filter((c: any) => c.known_tracker).length
  if (trackerCount > 10) {
    recs.push({ urgency: 'SHORT-TERM', text: `${trackerCount} known trackers detected. Install uBlock Origin (Firefox/Chrome) and enable the EasyPrivacy + Fanboy's Annoyance filter lists.` })
  }

  // Generic ongoing
  recs.push({ urgency: 'ONGOING', text: 'Run a full Doxshield scan weekly to monitor changes in your data sovereignty posture.' })
  recs.push({ urgency: 'ONGOING', text: 'Review your installed applications regularly and uninstall apps from high-risk jurisdictions that you no longer actively use.' })

  const urgent = recs.filter(r => r.urgency === 'URGENT')
  const shortTerm = recs.filter(r => r.urgency === 'SHORT-TERM')
  const ongoing = recs.filter(r => r.urgency === 'ONGOING')

  const urgencyColor: Record<string, string> = {
    URGENT: '#EF4444',
    'SHORT-TERM': '#F59E0B',
    ONGOING: '#3B82F6',
  }
  const urgencyBg: Record<string, string> = {
    URGENT: '#EF444422',
    'SHORT-TERM': '#F59E0B22',
    ONGOING: '#3B82F622',
  }

  function recGroup(items: Recommendation[], label: string) {
    if (items.length === 0) return ''
    const urgency = items[0].urgency
    return `
    <div class="rec-group">
      <div class="rec-group-header">
        <span class="rec-badge" style="background:${urgencyBg[urgency]};color:${urgencyColor[urgency]};border:1px solid ${urgencyColor[urgency]}44">${label}</span>
      </div>
      ${items.map(r => `
      <div class="rec-item" style="border-left:3px solid ${urgencyColor[r.urgency]}">
        <p>${esc(r.text)}</p>
      </div>`).join('')}
    </div>`
  }

  return `
  <!-- PAGE 6: RECOMMENDATIONS -->
  <div class="page last-page">
    <div class="page-header">
      <div class="page-header-left">
        <div class="section-eyebrow">Actionable Recommendations</div>
        <h1 class="section-title">Improving Your Data Sovereignty</h1>
      </div>
    </div>

    <p class="section-desc">
      Based on your scan results, the following actions are recommended to improve your data sovereignty score.
      Items are prioritised by urgency and potential privacy impact.
    </p>

    ${recGroup(urgent, 'URGENT — Action Required')}
    ${recGroup(shortTerm, 'SHORT-TERM — Within 30 days')}
    ${recGroup(ongoing, 'ONGOING — Regular Maintenance')}

    <!-- Final note -->
    <div class="final-note">
      <strong>About Doxshield</strong><br>
      Doxshield is a macOS data sovereignty monitor that helps you understand where your data goes and who controls it.
      All analysis is performed locally on your device — your scan results are never sent to external servers.
    </div>

    <div class="page-footer">
      Doxshield &middot; Data Sovereignty Report &middot; ${fmt(data.generatedAt)} &middot; Page <span class="pagenum"></span>
    </div>
  </div>`
}

// ─── Main HTML builder ────────────────────────────────────────────────────────

function buildHTML(data: {
  user: any
  overall: any
  apps: any[]
  connections: any[]
  cookies: any[]
  cookieStats: any
  lastScanAt: string | null
  generatedAt: Date
}): string {
  const css = `
    @page { size: A4; margin: 0; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      font-size: 12px;
      color: #1e293b;
      background: white;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    /* ── Page layout ── */
    .page {
      width: 210mm;
      min-height: 297mm;
      padding: 0;
      position: relative;
      page-break-after: always;
      background: white;
      overflow: hidden;
    }
    .page:not(.cover-page) {
      padding: 16mm 18mm 24mm 18mm;
    }
    .last-page { page-break-after: auto; }

    /* ── Cover page ── */
    .cover-page {
      display: flex;
      flex-direction: column;
      padding: 0;
    }
    .cover-header {
      background: #0f172a;
      padding: 28px 36px 24px 36px;
      color: white;
    }
    .cover-logo-row {
      display: flex;
      align-items: center;
      gap: 14px;
    }
    .cover-title {
      font-size: 26px;
      font-weight: 800;
      letter-spacing: 3px;
      color: white;
    }
    .cover-subtitle {
      font-size: 13px;
      color: #94a3b8;
      letter-spacing: 0.5px;
      margin-top: 2px;
    }
    .cover-score-section {
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 44px 36px 32px 36px;
      gap: 12px;
    }
    .score-circle-wrap {
      filter: drop-shadow(0 4px 16px rgba(59,130,246,0.2));
    }
    .score-label {
      font-size: 14px;
      font-weight: 600;
      color: #475569;
      letter-spacing: 0.5px;
    }
    .risk-badge {
      padding: 5px 18px;
      border-radius: 100px;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 1.5px;
    }
    .cover-meta {
      background: #f8fafc;
      border-top: 1px solid #e2e8f0;
      border-bottom: 1px solid #e2e8f0;
      padding: 20px 36px;
      margin: 0 0 auto 0;
    }
    .cover-meta-row {
      display: flex;
      gap: 16px;
      padding: 5px 0;
      border-bottom: 1px solid #e2e8f0;
    }
    .cover-meta-row:last-child { border-bottom: none; }
    .meta-label {
      font-size: 11px;
      color: #94a3b8;
      min-width: 100px;
      font-weight: 500;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .meta-value {
      font-size: 11px;
      color: #1e293b;
      font-weight: 600;
    }
    .cover-footer {
      padding: 14px 36px;
      font-size: 10px;
      color: #94a3b8;
      background: #0f172a;
      margin-top: auto;
      text-align: center;
      letter-spacing: 0.5px;
    }

    /* ── Page header ── */
    .page-header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      padding-bottom: 12px;
      margin-bottom: 16px;
      border-bottom: 2px solid #0f172a;
    }
    .section-eyebrow {
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: #3B82F6;
      font-weight: 600;
      margin-bottom: 3px;
    }
    .section-title {
      font-size: 20px;
      font-weight: 800;
      color: #0f172a;
    }
    .risk-badge-lg {
      padding: 5px 16px;
      border-radius: 100px;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 1.5px;
      margin-top: 4px;
    }
    .section-desc {
      font-size: 11px;
      color: #64748b;
      margin-bottom: 14px;
      line-height: 1.5;
    }

    /* ── Metric cards ── */
    .metric-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 10px;
      margin-bottom: 18px;
    }
    .metric-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 12px 14px;
    }
    .metric-value {
      font-size: 22px;
      font-weight: 800;
      line-height: 1;
      margin-bottom: 4px;
    }
    .metric-label {
      font-size: 10px;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-weight: 500;
    }

    /* ── Risk bars ── */
    .sub-section { margin-bottom: 16px; }
    .sub-heading {
      font-size: 12px;
      font-weight: 700;
      color: #0f172a;
      margin-bottom: 8px;
      padding-bottom: 4px;
      border-bottom: 1px solid #e2e8f0;
    }
    .risk-bars { display: flex; flex-direction: column; gap: 8px; }
    .risk-bar-row { display: flex; align-items: center; gap: 10px; }
    .risk-bar-label { font-size: 11px; color: #475569; min-width: 130px; }
    .risk-bar-track {
      flex: 1;
      height: 8px;
      background: #e2e8f0;
      border-radius: 4px;
      overflow: hidden;
    }
    .risk-bar-fill { height: 100%; border-radius: 4px; }
    .risk-bar-score { font-size: 11px; font-weight: 700; min-width: 28px; text-align: right; }

    /* ── Top apps ── */
    .top-apps-list { display: flex; flex-direction: column; gap: 4px; }
    .top-app-row {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 6px 8px;
      border-radius: 6px;
      background: #f8fafc;
    }
    .top-app-rank { font-size: 10px; font-weight: 700; color: #94a3b8; min-width: 16px; }
    .top-app-name { font-size: 11px; font-weight: 600; color: #1e293b; flex: 1; }
    .top-app-score { font-size: 11px; font-weight: 700; min-width: 28px; text-align: right; }
    .top-app-factor { font-size: 10px; color: #64748b; flex: 1; }

    /* ── Tables ── */
    .data-table {
      border-collapse: collapse;
      width: 100%;
      margin-bottom: 12px;
      font-size: 11px;
    }
    .data-table thead tr {
      background: #0f172a;
      color: white;
    }
    .data-table thead th {
      padding: 8px 10px;
      text-align: left;
      font-size: 10px;
      font-weight: 600;
      letter-spacing: 0.5px;
      text-transform: uppercase;
    }
    .data-table tbody td {
      padding: 7px 10px;
      border-bottom: 1px solid #f1f5f9;
      color: #334155;
    }
    .app-name-cell { max-width: 140px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

    /* ── Risk pills ── */
    .risk-pill {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 100px;
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.5px;
    }

    /* ── Findings list ── */
    .findings-list {
      padding-left: 16px;
      display: flex;
      flex-direction: column;
      gap: 5px;
    }
    .findings-list li {
      font-size: 11px;
      color: #334155;
      line-height: 1.5;
    }

    /* ── VPN box ── */
    .vpn-box {
      background: #eff6ff;
      border: 1px solid #bfdbfe;
      border-radius: 8px;
      padding: 10px 14px;
      margin-bottom: 14px;
    }
    .vpn-box-title { font-size: 12px; font-weight: 700; color: #1d4ed8; margin-bottom: 4px; }
    .vpn-box-body { font-size: 11px; color: #1e40af; line-height: 1.4; }

    /* ── Cookie stat boxes ── */
    .stat-boxes {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      margin-bottom: 18px;
    }
    .stat-box {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 14px;
      text-align: center;
    }
    .stat-value { font-size: 24px; font-weight: 800; line-height: 1; margin-bottom: 5px; }
    .stat-label { font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }

    /* ── Two column layout ── */
    .two-col {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
      margin-bottom: 16px;
    }

    /* ── Recommendations ── */
    .rec-group { margin-bottom: 14px; }
    .rec-group-header { margin-bottom: 7px; }
    .rec-badge {
      display: inline-block;
      padding: 3px 12px;
      border-radius: 100px;
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 1px;
    }
    .rec-item {
      background: #f8fafc;
      border-radius: 6px;
      padding: 10px 12px;
      margin-bottom: 5px;
    }
    .rec-item p { font-size: 11px; color: #334155; line-height: 1.5; }

    /* ── Final note ── */
    .final-note {
      background: #f0f9ff;
      border: 1px solid #bae6fd;
      border-radius: 8px;
      padding: 12px 16px;
      font-size: 11px;
      color: #0c4a6e;
      line-height: 1.6;
      margin-top: 16px;
    }

    /* ── Scan note ── */
    .scan-note {
      font-size: 10px;
      color: #94a3b8;
      font-style: italic;
      margin-top: 6px;
    }

    /* ── Page footer ── */
    .page-footer {
      position: absolute;
      bottom: 8mm;
      left: 18mm;
      right: 18mm;
      font-size: 9px;
      color: #94a3b8;
      border-top: 1px solid #e2e8f0;
      padding-top: 5px;
      text-align: center;
      letter-spacing: 0.3px;
    }
  `

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Doxshield Data Sovereignty Report</title>
  <style>${css}</style>
</head>
<body>
  ${buildCover(data)}
  ${buildExecSummary(data)}
  ${buildAppAnalysis(data)}
  ${buildNetworkAnalysis(data)}
  ${buildCookieAnalysis(data)}
  ${buildRecommendations(data)}
</body>
</html>`
}

// ─── Public export ────────────────────────────────────────────────────────────

export async function exportReport(store: StoreState): Promise<void> {
  // 1. Fetch fresh network + cookie data
  const [connRes, cookieRes] = await Promise.allSettled([
    fetch(`${SIDECAR_BASE}/api/network/live`).then(r => r.json()),
    fetch(`${SIDECAR_BASE}/api/cookies`).then(r => r.json()),
  ])

  const connections =
    connRes.status === 'fulfilled'
      ? Array.isArray(connRes.value) ? connRes.value : []
      : store.connections || []

  const cookieData = cookieRes.status === 'fulfilled' ? cookieRes.value : {}
  const cookies = cookieData.cookies ?? store.cookies ?? []
  const cookieStats = cookieData.stats ?? {}

  const data = {
    user: store.user,
    overall: store.overallRisk,
    apps: store.apps || [],
    connections,
    cookies,
    cookieStats,
    lastScanAt: store.lastScanAt,
    generatedAt: new Date(),
  }

  const html = buildHTML(data)
  const filename = `Doxshield-Report-${data.generatedAt.toISOString().split('T')[0]}.pdf`

  const savedPath = await window.sovereign?.savePdf(html, filename)
  if (savedPath) {
    window.sovereign?.openExternal(`file://${savedPath}`)
  }
}
