console.log('process.type:', process.type)
console.log('process.versions.electron:', process.versions.electron)
const { app } = require('electron')
console.log('app type:', typeof app)
if (app) app.quit()
